#!/bin/bash

bat="$(ls /sys/class/power_supply | grep BAT)"
if [ "$bat" ]; then
  capacity="$(cat "/sys/class/power_supply/$bat/capacity")"
  status="$(cat "/sys/class/power_supply/$bat/status")"
  remaining_time="$(acpi -b | cut -d ' ' -f 5,6)"
  if [ "$capacity" -lt 10 ]; then
    icon=$(if [ "$status" = "Charging" ]; then echo 󰢜; else echo 󰁺; fi)
  elif [ "$capacity" -lt 20 ]; then
    icon=$(if [ "$status" = "Charging" ]; then echo 󰂆; else echo 󰁻; fi)
  elif [ "$capacity" -lt 30 ]; then
    icon=$(if [ "$status" = "Charging" ]; then echo 󰂇; else echo 󰁼; fi)
  elif [ "$capacity" -lt 40 ]; then
    icon=$(if [ "$status" = "Charging" ]; then echo 󰂈; else echo 󰁽; fi)
  elif [ "$capacity" -lt 50 ]; then
    icon=$(if [ "$status" = "Charging" ]; then echo 󰢝; else echo 󰁾; fi)
  elif [ "$capacity" -lt 60 ]; then
    icon=$(if [ "$status" = "Charging" ]; then echo 󰂉; else echo 󰁿; fi)
  elif [ "$capacity" -lt 70 ]; then
    icon=$(if [ "$status" = "Charging" ]; then echo 󰢞; else echo 󰂀; fi)
  elif [ "$capacity" -lt 80 ]; then
    icon=$(if [ "$status" = "Charging" ]; then echo 󰂊; else echo 󰂁; fi)
  elif [ "$capacity" -lt 90 ]; then
    icon=$(if [ "$status" = "Charging" ]; then echo 󰂋; else echo 󰂂; fi)
  else
    icon=$(if [ "$status" = "Charging" ]; then echo 󰂅; else echo 󰁹; fi)
  fi
  echo "$icon $capacity% [$remaining_time]"
fi
